export const products = [
    {
      id: 1,
      name: "Alienware m18 Gaming Laptop",
      originalPrice: "₦950,000",
      salePrice: "₦849,000",
      onSale: true,
      category: "Laptops",
      tag: "SALE",
      sku: "OSH-001",
      desc: "Dominate every game with the Alienware m18. Powered by the latest Intel Core i9 processor and NVIDIA RTX 4090 graphics, this beast delivers uncompromising performance for serious gamers.",
      additionalInfo: "Processor: Intel Core i9 | RAM: 32GB DDR5 | Storage: 1TB NVMe SSD | Display: 18-inch QHD 165Hz | OS: Windows 11 Home",
      img: "/images/alienware.jpg"
    },
    {
      id: 2,
      name: "Home Appliances Bundle",
      originalPrice: null,
      salePrice: "₦280,000",
      onSale: false,
      category: "Home Appliances",
      tag: null,
      sku: "OSH-002",
      desc: "Upgrade your home with our curated appliances bundle. Includes a microwave, electric kettle, and blender — all energy-efficient and built to last in everyday Nigerian homes.",
      additionalInfo: "Includes: 20L Microwave, 1.7L Kettle, 1.5L Blender | Power: 220–240V | Warranty: 1 Year",
      img: "/images/appliances.jpg"
    },
    {
      id: 3,
      name: "Dell Inspiron 15 Laptop",
      originalPrice: null,
      salePrice: "₦420,000",
      onSale: false,
      category: "Laptops",
      tag: null,
      sku: "OSH-003",
      desc: "The Dell Inspiron 15 is the perfect everyday laptop for students and professionals. Fast, reliable, and affordable — it handles everything from documents to video calls with ease.",
      additionalInfo: "Processor: Intel Core i5 12th Gen | RAM: 8GB DDR4 | Storage: 512GB SSD | Display: 15.6-inch FHD | OS: Windows 11 Home",
      img: "/images/dell.jpg"
    },
    {
      id: 4,
      name: "HP EliteBook 840 G10",
      originalPrice: "₦680,000",
      salePrice: "₦589,000",
      onSale: true,
      category: "Laptops",
      tag: "SALE",
      sku: "OSH-004",
      desc: "Built for business, the HP EliteBook 840 G10 combines enterprise-grade security with sleek portability. Ideal for executives and remote workers who need reliability on the go.",
      additionalInfo: "Processor: Intel Core i7 13th Gen | RAM: 16GB DDR5 | Storage: 512GB SSD | Display: 14-inch FHD IPS | OS: Windows 11 Pro",
      img: "/images/elitebook.jpg"
    },
    {
      id: 5,
      name: "Home Appliances Set",
      originalPrice: "₦195,000",
      salePrice: "₦155,000",
      onSale: true,
      category: "Home Appliances",
      tag: "SALE",
      sku: "OSH-005",
      desc: "A complete set of quality home appliances to make your daily routine easier. From cooking to cleaning, everything you need is right here at an unbeatable price.",
      additionalInfo: "Set includes: Iron, Standing Fan, Rice Cooker | Power: 220V | Warranty: 1 Year | Colour: White/Grey",
      img: "/images/homeappliances.jpg"
    },
    {
      id: 6,
      name: "Apple iPhone 16",
      originalPrice: null,
      salePrice: "₦899,000",
      onSale: false,
      category: "Smartphones",
      tag: null,
      sku: "OSH-006",
      desc: "The iPhone 16 brings next-level performance with the A18 chip, a stunning Super Retina XDR display, and a pro-grade camera system. Experience Apple at its finest.",
      additionalInfo: "Storage: 128GB | Display: 6.1-inch OLED | Camera: 48MP Main | Battery: 3,561mAh | OS: iOS 18 | Colour: Black, White, Pink, Blue",
      img: "/images/iphone16.jpg"
    },
    {
      id: 7,
      name: "Apple iPhone 17",
      originalPrice: null,
      salePrice: "₦1,150,000",
      onSale: false,
      category: "Smartphones",
      tag: "NEW",
      sku: "OSH-007",
      desc: "The all-new iPhone 17 pushes the boundaries of what a smartphone can do. Featuring Apple Intelligence, an upgraded camera array, and the fastest chip ever in an iPhone.",
      additionalInfo: "Storage: 256GB | Display: 6.3-inch ProMotion OLED | Camera: 48MP Main + 12MP Ultra Wide | Battery: 4,000mAh | OS: iOS 18",
      img: "/images/iphone17.jpg"
    },
    {
      id: 8,
      name: "JBL Tune 770NC Headphones",
      originalPrice: null,
      salePrice: "₦89,000",
      onSale: false,
      category: "Audio",
      tag: null,
      sku: "OSH-008",
      desc: "Block out the noise and lose yourself in music with JBL Tune 770NC. Features adaptive noise cancellation, 70-hour battery life, and JBL's signature deep bass sound.",
      additionalInfo: "Type: Over-Ear | Battery Life: 70 hours | Noise Cancellation: Yes (Adaptive ANC) | Connectivity: Bluetooth 5.3 | Foldable: Yes",
      img: "/images/jblheaphones.jpg"
    },
    {
      id: 9,
      name: "JBL Xtreme 3 Speaker",
      originalPrice: "₦145,000",
      salePrice: "₦119,000",
      onSale: true,
      category: "Audio",
      tag: "SALE",
      sku: "OSH-009",
      desc: "Take the party anywhere with the JBL Xtreme 3. Powerful 100W stereo sound, IP67 waterproof rating, and 15 hours of playtime make it the ultimate outdoor speaker.",
      additionalInfo: "Output: 100W | Battery Life: 15 hours | Waterproof: IP67 | Connectivity: Bluetooth 5.1 | Weight: 1.9kg | Colour: Black, Blue, Camouflage",
      img: "/images/jblspeaker.jpg"
    },
    {
      id: 10,
      name: "Lexmark CS531dw Printer",
      originalPrice: "₦210,000",
      salePrice: "₦178,000",
      onSale: true,
      category: "Home Appliances",
      tag: "SALE",
      sku: "OSH-010",
      desc: "Print faster, smarter, and more efficiently with the Lexmark CS531dw. This colour laser printer is built for busy offices that need reliable, high-quality output every day.",
      additionalInfo: "Type: Colour Laser | Speed: 26ppm | Connectivity: Wi-Fi, USB, Ethernet | Duplex: Yes | Monthly Duty Cycle: Up to 75,000 pages",
      img: "/images/lexmark.jpg"
    },
    {
      id: 11,
      name: "Apple MacBook Pro 14-inch (M3)",
      originalPrice: "₦1,450,000",
      salePrice: "₦1,299,000",
      onSale: true,
      category: "Laptops",
      tag: "SALE",
      sku: "OSH-011",
      desc: "The MacBook Pro 14-inch with M3 chip is a powerhouse for creatives and developers. Stunning Liquid Retina XDR display, all-day battery life, and performance that feels effortless.",
      additionalInfo: "Chip: Apple M3 | RAM: 18GB Unified Memory | Storage: 512GB SSD | Display: 14.2-inch Liquid Retina XDR | Battery: Up to 22 hours | OS: macOS Sonoma",
      img: "/images/macbook.jpg"
    },
    {
      id: 12,
      name: "Apple MacBook Air 15-inch (M2)",
      originalPrice: null,
      salePrice: "₦1,050,000",
      onSale: false,
      category: "Laptops",
      tag: null,
      sku: "OSH-012",
      desc: "Thin, light, and incredibly capable — the MacBook Air 15-inch with M2 is perfect for students and professionals who want Apple performance without the Pro price tag.",
      additionalInfo: "Chip: Apple M2 | RAM: 8GB Unified Memory | Storage: 256GB SSD | Display: 15.3-inch Liquid Retina | Battery: Up to 18 hours | OS: macOS Sonoma",
      img: "/images/macbook1.jpg"
    },
    {
      id: 13,
      name: "Sony ZV-E10 II Camera",
      originalPrice: null,
      salePrice: "₦520,000",
      onSale: false,
      category: "Cameras",
      tag: "NEW",
      sku: "OSH-013",
      desc: "The Sony ZV-E10 II is made for content creators who want cinematic quality without the complexity. Compact, interchangeable lens design with 4K video and real-time autofocus.",
      additionalInfo: "Sensor: 26MP APS-C Exmor R | Video: 4K 60fps | Autofocus: AI-based Real-Time Tracking | Mount: Sony E-Mount | Battery Life: 570 shots",
      img: "/images/sonycamera.jpg"
    },
    {
      id: 14,
      name: "Hisense 55-inch 4K UHD Smart TV",
      originalPrice: "₦380,000",
      salePrice: "₦319,000",
      onSale: true,
      category: "TVs",
      tag: "SALE",
      sku: "OSH-014",
      desc: "Transform your living room with the Hisense 55-inch 4K Smart TV. Vivid colours, Dolby Vision HDR, and built-in Netflix, YouTube and Prime Video make every night a cinema night.",
      additionalInfo: "Screen Size: 55 inches | Resolution: 4K UHD (3840x2160) | HDR: Dolby Vision & HDR10 | Smart OS: VIDAA | HDMI Ports: 3 | Wi-Fi: Yes",
      img: "/images/tv.jpg"
    },
    {
      id: 15,
      name: "LG 65-inch OLED Smart TV",
      originalPrice: "₦850,000",
      salePrice: "₦749,000",
      onSale: true,
      category: "TVs",
      tag: "SALE",
      sku: "OSH-015",
      desc: "Experience true blacks and infinite contrast with the LG 65-inch OLED TV. With WebOS, Dolby Atmos, and a razor-thin design, this is the premium TV your home deserves.",
      additionalInfo: "Screen Size: 65 inches | Panel: OLED | Resolution: 4K UHD | HDR: Dolby Vision IQ, HDR10 | Smart OS: WebOS 23 | HDMI Ports: 4 | Wi-Fi: Yes",
      img: "/images/tv2.jpg"
    },
  ];